apiVersion: apps/v1
kind: Deployment
metadata:
  name: encontros-tech
  namespace: bootcamp-ai-devops
  labels:
    app: encontros-tech
spec:
  selector:
    matchLabels:
      app: encontros-tech
  template:
    metadata:
      labels:
        app: encontros-tech
    spec:
      containers:
      - name: encontros-tech
        image: brhrmaster/bootcamp-conversao-distancia:v1
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: DATABASE_URL
          value: "postgresql://*****:********@db-postgresql-homologacao-do-user-28212959-0.e.db.ondigitalocean.com:25060/encontros_tech?sslmode=require"
        - name: APP_TITLE
          value: "Encontros Tech"
        - name: DEBUG
          value: "false"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8000"
        - name: LOG_LEVEL
          value: "INFO"
        - name: LOG_FORMAT
          value: "simple"
        - name: SERVICE_NAME
          value: "encontros-tech"
        - name: SERVICE_VERSION
          value: "1.0.0"
        - name: PROMETHEUS_MULTIPROC_DIR
          value: "/tmp/prometheus_multiproc"
---
apiVersion: v1
kind: Service
metadata:
  name: encontros-tech
  namespace: bootcamp-ai-devops
  labels:
    app: encontros-tech
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: encontros-tech
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: encontros-tech
  namespace: bootcamp-ai-devops
  labels:
    app: encontros-tech
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: encontros-tech
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75